apiVersion: autoscaling/v2beta2 
kind: HorizontalPodAutoscaler
metadata:
  name: petclinic-mem-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: petclinic-deployment 
  minReplicas: 1 
  maxReplicas: 5
  metrics: 
  - type: Resource
    resource:
      name: memory 
      target:
        type: Utilization 
        averageValue: 50Mi
